### ISSUE TITLE
Crash on encoding error

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/pshtt#46]
Got a `requests.exceptions.ChunkedEncodingError` during scanning that caused a stack trace. Should be handled more gracefully.

```
Traceback (most recent call last):
  File "/opt/install/pyenv/versions/2.7.11/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.3', 'console_scripts', 'pshtt')()
  File "/opt/scan/pshtt/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/opt/scan/pshtt/pshtt/pshtt.py", line 871, in inspect_domains
    preload_pending = fetch_preload_pending()
  File "/opt/scan/pshtt/pshtt/pshtt.py", line 770, in fetch_preload_pending
    request = requests.get(pending_url)
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/
api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/
api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/
sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
 File "/opt/install/pyenv/versions/2.7.11/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
```

**Comment by konklone** [comment]
Not enough information to reproduce.
