### ISSUE TITLE
Debian 8 - PIP error trying to install pshtt

### ISSUE THREAD

**Issue by QuarantineENG** [dhs-ncats/pshtt#64]
If I use pip or pip3 this errors out on me when trying to install pshtt.

Running setup.py (path:/tmp/pip-build-wdme68eo/nassl/setup.py) egg_info for package nassl
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-wdme68eo/nassl/setup.py", line 67, in <module>
        OPENSSL_LIB_INSTALL_PATH = OPENSSL_INSTALL_PATH_DICT[CURRENT_PLATFORM]
    KeyError: None
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-wdme68eo/nassl/setup.py", line 67, in <module>

    OPENSSL_LIB_INSTALL_PATH = OPENSSL_INSTALL_PATH_DICT[CURRENT_PLATFORM]

KeyError: None

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-wdme68eo/nassl
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-wdme68eo/nassl

**Comment by konklone** [comment]
For now, pshtt still requires Python 2. See https://github.com/dhs-ncats/pshtt/issues/4 for the relevant issue.

**Comment by konklone** [comment]
Closing since we identified the issue as needing Python 2.
