### ISSUE TITLE
AttributeError thrown when there is a hostname validation error

### ISSUE THREAD

**Issue by redshiftzero** [dhs-ncats/pshtt#71]
Hit an unhandled exception while scanning `cbc.ca`:

```sh
$ pshtt cbc.ca --json
Certificate did not match expected hostname: cbc.ca. Certificate: {'subjectAltName': [('DNS', '*.akamaihd.net'), ('DNS', '*.akamaihd-staging.net'), ('DNS', '*.akamaized-staging.net'), ('DNS', '*.akamaized.net'), ('DNS', 'a248.e.akamai.net')], 'subject': ((('commonName', u'a248.e.akamai.net'),),)}
Traceback (most recent call last):
  File "/usr/local/bin/pshtt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/local/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
    results.append(inspect(domain))
  File "/usr/local/lib/python2.7/site-packages/pshtt/pshtt.py", line 63, in inspect
    basic_check(domain.https)
  File "/usr/local/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
    https_check(endpoint)
  File "/usr/local/lib/python2.7/site-packages/pshtt/pshtt.py", line 335, in https_check
    except nassl.x509_certificate.X509HostnameValidationError:
AttributeError: 'module' object has no attribute 'x509_certificate'
```

**Comment by h-m-f-t** [comment]
Heyo @redshiftzero. Are you using the latest version in the repo or pip? 

Here's my output with 0.1.6 in master:
```sh
$ pshtt cbc.ca --json
Certificate did not match expected hostname: cbc.ca. Certificate: {'crlDistributionPoints': (u'http://ss.symcb.com/ss.crl',), 'subjectAltName': (('DNS', '*.akamaihd.net'), ('DNS', '*.akamaized.net'), ('DNS', '*.akamaized-staging.net'), ('DNS', '*.akamaihd-staging.net'), ('DNS', 'a248.e.akamai.net')), 'notBefore': u'Mar  7 00:00:00 2017 GMT', 'caIssuers': (u'http://ss.symcb.com/ss.crt',), 'OCSP': (u'http://ss.symcd.com',), 'serialNumber': u'21C0AE35B8240503E5A5894F40D5BFEB', 'notAfter': 'May  6 23:59:59 2018 GMT', 'version': 3L, 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'Massachusetts'),), (('localityName', u'Cambridge'),), (('organizationName', u'Akamai Technologies, Inc.'),), (('commonName', u'a248.e.akamai.net'),)), 'issuer': ((('countryName', u'US'),), (('organizationName', u'Symantec Corporation'),), (('organizationalUnitName', u'Symantec Trust Network'),), (('commonName', u'Symantec Class 3 Secure Server CA - G4'),))}
Error validating certificate.
Known error in sslyze 1.X with EC public keys. See https://github.com/nabla-c0d3/sslyze/issues/215
[
  {
    "Base Domain": "cbc.ca", 
    "Canonical URL": "http://www.cbc.ca", 
    "Defaults to HTTPS": false, 
    "Domain": "cbc.ca", 
    "Domain Enforces HTTPS": false, 
    "Domain Supports HTTPS": false, 
    "Domain Uses Strong HSTS": false, 
    "Downgrades HTTPS": true, 
    "HSTS": false, 
    "HSTS Base Domain Preloaded": false, 
    "HSTS Entire Domain": null, 
    "HSTS Header": null, 
    "HSTS Max Age": null, 
    "HSTS Preload Pending": false, 
    "HSTS Preload Ready": false, 
    "HSTS Preloaded": false, 
    "HTTPS Bad Chain": null, 
    "HTTPS Bad Hostname": null, 
    "HTTPS Expired Cert": null, 
    "Live": true, 
    "Redirect": false, 
    "Redirect To": null, 
    "Strictly Forces HTTPS": false, 
    "Valid HTTPS": true, 
    "endpoints": {
      "http": {
        "headers": {
          "Connection": "keep-alive", 
          "Content-Length": "0", 
          "Date": "Wed, 24 May 2017 17:02:53 GMT", 
          "Location": "http://www.cbc.ca/", 
          "Server": "AkamaiGHost"
        }, 
        "live": true, 
        "redirect": true, 
        "redirect_eventually_to": "http://www.cbc.ca/", 
        "redirect_eventually_to_external": false, 
        "redirect_eventually_to_http": true, 
        "redirect_eventually_to_https": false, 
        "redirect_eventually_to_subdomain": true, 
        "redirect_immediately_to": "http://www.cbc.ca/", 
        "redirect_immediately_to_external": false, 
        "redirect_immediately_to_http": true, 
        "redirect_immediately_to_https": false, 
        "redirect_immediately_to_subdomain": true, 
        "redirect_immediately_to_www": null, 
        "status": 301, 
        "url": "http://cbc.ca"
      }, 
      "https": {
        "headers": {
          "Connection": "keep-alive", 
          "Content-Length": "0", 
          "Date": "Wed, 24 May 2017 17:02:54 GMT", 
          "Location": "https://www.cbc.ca/", 
          "Server": "AkamaiGHost"
        }, 
        "hsts": false, 
        "hsts_all_subdomains": null, 
        "hsts_header": null, 
        "hsts_max_age": null, 
        "hsts_preload": null, 
        "https_bad_chain": null, 
        "https_bad_hostname": null, 
        "https_expired_cert": null, 
        "https_valid": null, 
        "live": true, 
        "redirect": true, 
        "redirect_eventually_to": "http://www.cbc.ca/", 
        "redirect_eventually_to_external": false, 
        "redirect_eventually_to_http": true, 
        "redirect_eventually_to_https": false, 
        "redirect_eventually_to_subdomain": true, 
        "redirect_immediately_to": "https://www.cbc.ca/", 
        "redirect_immediately_to_external": false, 
        "redirect_immediately_to_http": false, 
        "redirect_immediately_to_https": true, 
        "redirect_immediately_to_subdomain": true, 
        "redirect_immediately_to_www": null, 
        "status": 301, 
        "url": "https://cbc.ca"
      }, 
      "httpswww": {
        "headers": {
          "Connection": "keep-alive", 
          "Content-Length": "0", 
          "Date": "Wed, 24 May 2017 17:02:54 GMT", 
          "Location": "http://www.cbc.ca/", 
          "Server": "AkamaiGHost", 
          "Set-Cookie": "akaas_feed=2147483647~rv=95~id=c866e93b760b049ee3053645f7ff3704; path=/"
        }, 
        "hsts": false, 
        "hsts_all_subdomains": null, 
        "hsts_header": null, 
        "hsts_max_age": null, 
        "hsts_preload": null, 
        "https_bad_chain": null, 
        "https_bad_hostname": null, 
        "https_expired_cert": null, 
        "https_valid": true, 
        "live": true, 
        "redirect": true, 
        "redirect_eventually_to": "http://www.cbc.ca/", 
        "redirect_eventually_to_external": false, 
        "redirect_eventually_to_http": true, 
        "redirect_eventually_to_https": false, 
        "redirect_eventually_to_subdomain": false, 
        "redirect_immediately_to": "http://www.cbc.ca/", 
        "redirect_immediately_to_external": false, 
        "redirect_immediately_to_http": true, 
        "redirect_immediately_to_https": false, 
        "redirect_immediately_to_subdomain": false, 
        "redirect_immediately_to_www": null, 
        "status": 302, 
        "url": "https://www.cbc.ca"
      }, 
      "httpwww": {
        "headers": {
          "Cache-Control": "max-age=35", 
          "Connection": "keep-alive", 
          "Content-Encoding": "gzip", 
          "Content-Length": "23037", 
          "Content-Type": "text/html", 
          "Date": "Wed, 24 May 2017 17:02:53 GMT", 
          "Server": "Apache/2.2.15 (Red Hat)", 
          "Set-Cookie": "akaas_feed=2147483647~rv=61~id=3aa5d798cd8c041a08f7708e6fc2fb18; path=/, akaas_feed=2147483647~rv=85~id=9b3371e0f7c93ae8d8556e946886deb2; path=/, akaas_feed=2147483647~rv=82~id=73acb87502ed7d7d1ba4f6fe99314ec5; path=/, akaas_feed=2147483647~rv=6~id=deff66c3c2eed6cc0e326c00d880be7a; path=/, akaas_feed=2147483647~rv=23~id=3cf8e6c257bff7dd814ba5dbbeaf99ee; path=/, akaas_feed=2147483647~rv=14~id=3d919a225416eb8b3b91aaa123db7078; path=/, akaas_feed=2147483647~rv=32~id=83045eb1e115694649efdec8788d55b3; path=/, akaas_feed=2147483647~rv=35~id=73f9cf4497574582fd9a4f6339615ca5; path=/", 
          "Vary": "Accept-Encoding", 
          "X-Origin-Server": "static01_cache01"
        }, 
        "live": true, 
        "redirect": null, 
        "redirect_eventually_to": null, 
        "redirect_eventually_to_external": null, 
        "redirect_eventually_to_http": null, 
        "redirect_eventually_to_https": null, 
        "redirect_eventually_to_subdomain": null, 
        "redirect_immediately_to": null, 
        "redirect_immediately_to_external": null, 
        "redirect_immediately_to_http": null, 
        "redirect_immediately_to_https": null, 
        "redirect_immediately_to_subdomain": null, 
        "redirect_immediately_to_www": null, 
        "status": 200, 
        "url": "http://www.cbc.ca"
      }
    }
  }
]
```

**Comment by konklone** [comment]
Closing, but feel free to re-open if you can answer @h-m-f-t's question and can reproduce the issue.
